name: GitHub Actions Demo

on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v3
      - name: hello-world
        run: echo "Hello world"
      - name: run-python-script
        run: |
          pip install requirements.txt
          python ci.py
     
