name: GitHub Secrets Demo

on: [push]
jobs:
  secrets-demo:
    runs-on: ubuntu-latest
   
    steps:
      - name: Sample secret action
        with: # Set Azure credentials secret as an input
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
        env: # Or as an environment variable
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
      - name: echo secret
        run: |
            echo $credentials

  
