name: GitHub Secrets Demo

on: [push]
jobs:
  secrets-demo:
    runs-on: ubuntu-latest
   
    steps:
      - name: Sample secret action
   
        env: # Or as an environment variable
          credentials: ${{ secrets.GITOPS_SECRET }}
    
        run: |
            echo $credentials

  
