on: [push]
steps:
  - name: Sample secret action
    with: # Set Azure credentials secret as an input
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
    env: # Or as an environment variable
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
  - run-on : ubuntu-latest
  - run: |
      echo $credentials
  
